version: '3.9'
services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    ports:
      - '3307:3306'
    volumes:
      - ./data_db:/var/lib/mariadb


